services:
    os-projects:
        platform: linux/amd64
        image: ubuntu:22.04
        container_name: os-projects2
        stdin_open: true
        tty: true
        volumes:
            - ./xv6-proj0:/home/20251R0136COSE34103/xv6-proj0
            - ./xv6-proj1:/home/20251R0136COSE34103/xv6-proj1
            - ./xv6-proj2:/home/20251R0136COSE34103/xv6-proj2
